import ArithDyn.Nilpotence.Map
import ArithDyn.Nilpotence.Dense

/-!
# The elimination tool (paper §5.4, Lemmas 5.8–5.9, made elementary)

Let `Y = V(F) ⊆ 𝔸³` be a closed set all of whose points eventually reach `O`. We show that a
*nonzero* polynomial `d ∈ K[v,u]` vanishes on `π(Y ∩ U)`, `π(x,y,z) = (x/z, y/z)`; i.e. the
Zariski closure of `π(Y ∩ U)` is a proper closed subset of the torus (Lemma 5.9).

The proof uses that the fibres of `π` are one–dimensional: substituting `x = uz, y = vz` turns
`F` into polynomials in `z` over `R₂ = K[v,u]`; over the fraction field `L = Frac R₂` the ideal
they generate is principal, generated by some `G`. Clearing denominators and stripping powers of
`z` we get `G₀ = z^e G₁ ∈ R₂[z]` with `G₁(0) ≠ 0`.
* If `G₁` is constant, a nonzero constant multiple `C d` of `z^e` lies in the ideal, so `d`
  vanishes on `π(Y ∩ U)`.
* Otherwise we specialise at a point `(u₀,v₀)` of the escaping set `E` avoiding finitely many
  hypersurfaces, pick a nonzero root `z₀` of the specialised `G₁` (`K` algebraically closed), and
  obtain a point `(u₀z₀, v₀z₀, z₀) ∈ Y ∩ U` whose orbit never reaches `O` — a contradiction
  (this replaces Chevalley's theorem, Lemma 5.8).
-/

set_option autoImplicit false
set_option synthInstance.maxHeartbeats 400000

namespace ArithDyn.Nilpotence

open MvPolynomial Polynomial

variable {K : Type*} [Field K]

/-- The coordinate ring `K[v,u]` of the base plane (`X 0 = v`, `X 1 = u`). -/
abbrev R2 (K : Type*) [Field K] := MvPolynomial (Fin 2) K

/-- Its fraction field. -/
abbrev L (K : Type*) [Field K] := FractionRing (R2 K)

/-- Coefficientwise inclusion `R₂[z] → L[z]`. -/
noncomputable def φL : Polynomial (R2 K) →+* Polynomial (L K) :=
  Polynomial.mapRingHom (algebraMap (R2 K) (L K))

lemma φL_injective : Function.Injective (φL (K := K)) :=
  Polynomial.map_injective _ (IsFractionRing.injective (R2 K) (L K))

lemma φL_C (r : R2 K) : φL (Polynomial.C r) = Polynomial.C (algebraMap (R2 K) (L K) r) := by
  simp [φL]

lemma algebraMap_ne_zero {r : R2 K} (hr : r ≠ 0) : algebraMap (R2 K) (L K) r ≠ 0 :=
  (map_ne_zero_iff _ (IsFractionRing.injective (R2 K) (L K))).2 hr

/-- Clearing the denominators of one polynomial over `L`. -/
lemma exists_clear (h : Polynomial (L K)) :
    ∃ N : Polynomial (R2 K), ∃ b : R2 K, b ≠ 0 ∧
      φL N = Polynomial.C (algebraMap (R2 K) (L K) b) * h := by
  obtain ⟨b, hb, hN⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors (R2 K)) h
  refine ⟨IsLocalization.integerNormalization (nonZeroDivisors (R2 K)) h, b,
    nonZeroDivisors.ne_zero hb, ?_⟩
  rw [φL, Polynomial.coe_mapRingHom, hN, Algebra.smul_def, Polynomial.algebraMap_apply]

/-- If `φL G ∣ φL t` in `L[z]` then `C b * t = H * G` in `R₂[z]` for some `b ≠ 0`. -/
lemma exists_mul_eq_of_dvd {G t : Polynomial (R2 K)} (h : φL G ∣ φL t) :
    ∃ H : Polynomial (R2 K), ∃ b : R2 K, b ≠ 0 ∧ Polynomial.C b * t = H * G := by
  obtain ⟨h', hh'⟩ := h
  obtain ⟨N, b, hb, hN⟩ := exists_clear h'
  refine ⟨N, b, hb, φL_injective ?_⟩
  rw [map_mul, map_mul, φL_C, hh', hN]
  ring

/-- Membership in the extended ideal, with a common denominator: if `g ∈ φL(I)·L[z]` where
`I = span T` (`T` finite), then `C b * g ∈ φL(I)` for some `b ≠ 0`. -/
lemma exists_mem_span_of_mem_map (T : Finset (Polynomial (R2 K))) {g : Polynomial (L K)}
    (hg : g ∈ Ideal.map φL (Ideal.span (↑T : Set (Polynomial (R2 K))))) :
    ∃ b : R2 K, b ≠ 0 ∧ ∃ g₀ ∈ Ideal.span (↑T : Set (Polynomial (R2 K))),
      φL g₀ = Polynomial.C (algebraMap (R2 K) (L K) b) * g := by
  classical
  rw [Ideal.map_span, ← Finset.coe_image] at hg
  obtain ⟨c, -, hc⟩ := Submodule.mem_span_finset.1 hg
  -- `g = ∑_{t ∈ T} c (φL t) * φL t`
  have hsum : ∑ t ∈ T, c (φL t) * φL t = g := by
    rw [← hc, Finset.sum_image (fun x _ y _ h => φL_injective h)]
    simp [smul_eq_mul]
  -- clear the denominators of the finitely many coefficients
  choose N b hb hN using fun t : Polynomial (R2 K) => exists_clear (c (φL t))
  refine ⟨∏ t ∈ T, b t, Finset.prod_ne_zero_iff.2 (fun t _ => hb t), ?_⟩
  refine ⟨∑ t ∈ T, Polynomial.C (∏ t' ∈ T.erase t, b t') * N t * t, ?_, ?_⟩
  · exact Ideal.sum_mem _ (fun t ht => Ideal.mul_mem_left _ _ (Ideal.subset_span ht))
  · rw [← hsum, map_sum, Finset.mul_sum]
    refine Finset.sum_congr rfl (fun t ht => ?_)
    rw [map_mul, map_mul, φL_C, hN t]
    have : algebraMap (R2 K) (L K) (∏ t' ∈ T, b t') =
        algebraMap (R2 K) (L K) (∏ t' ∈ T.erase t, b t') * algebraMap (R2 K) (L K) (b t) := by
      rw [← Finset.prod_erase_mul _ _ ht, map_mul]
    rw [this, Polynomial.C_mul]
    ring

/-! ### Substitution `x = uz, y = vz` and specialisation -/

/-- The substitution `x ↦ u z, y ↦ v z, z ↦ z` into `R₂[z]` (`X 0 = v`, `X 1 = u` in `R₂`). -/
noncomputable def sub3 : MvPolynomial (Fin 3) K →ₐ[K] Polynomial (R2 K) :=
  MvPolynomial.aeval
    ![Polynomial.C (X 1) * Polynomial.X, Polynomial.C (X 0) * Polynomial.X, Polynomial.X]

/-- Specialisation at `(u, v, z₀)`: `R₂[z] → K`. -/
noncomputable def specialize (u v z₀ : K) : Polynomial (R2 K) →+* K :=
  (Polynomial.evalRingHom z₀).comp (Polynomial.mapRingHom (MvPolynomial.eval ![v, u]))

lemma specialize_apply (u v z₀ : K) (g : Polynomial (R2 K)) :
    specialize u v z₀ g = Polynomial.eval z₀ (Polynomial.map (MvPolynomial.eval ![v, u]) g) := rfl

lemma specialize_C (u v z₀ : K) (r : R2 K) :
    specialize u v z₀ (Polynomial.C r) = MvPolynomial.eval ![v, u] r := by
  simp [specialize]

lemma specialize_sub3 (u v z₀ : K) (f : MvPolynomial (Fin 3) K) :
    specialize u v z₀ (sub3 f) = MvPolynomial.eval ![u * z₀, v * z₀, z₀] f := by
  have : (specialize u v z₀).comp (sub3 (K := K)).toRingHom =
      (MvPolynomial.eval ![u * z₀, v * z₀, z₀] : MvPolynomial (Fin 3) K →+* K) := by
    apply MvPolynomial.ringHom_ext
    · intro a; simp [specialize, sub3]
    · intro i; fin_cases i <;> simp [specialize, sub3]
  have := RingHom.congr_fun this f
  simpa using this

/-- The zero set of a set of polynomials (a closed subset of `𝔸³`). -/
def V (F : Set (MvPolynomial (Fin 3) K)) : Set (Fin 3 → K) := {a | ∀ f ∈ F, MvPolynomial.eval a f = 0}

lemma not_reach_zero_of_Eset {u v z : K} (hE : (u, v) ∈ Eset K) (hz : z ≠ 0) :
    ¬ ∃ n, 1 ≤ n ∧ T^[n] ![u * z, v * z, z] = 0 := by
  rintro ⟨n, -, hn⟩
  obtain ⟨hu, hv, hu1, hesc⟩ := hE
  exact iterate_ne_zero_of_escaping hu hv hu1 hesc hz n hn

/-- **The elimination theorem** (Lemma 5.9 made elementary). If every point of the closed set
`V F` reaches `O`, then some nonzero `d ∈ K[v,u]` vanishes on `π(V F ∩ U)`. -/
theorem exists_vanishing_poly [IsAlgClosed K]
    (hfin : ∀ u : K, u ≠ 0 → ∃ M : ℕ, 0 < M ∧ u ^ M = 1)
    (F : Set (MvPolynomial (Fin 3) K))
    (hnil : ∀ y ∈ V F, ∃ n, 1 ≤ n ∧ T^[n] y = 0) :
    ∃ d : R2 K, d ≠ 0 ∧ ∀ y ∈ V F, inU y → MvPolynomial.eval ![y 1 / y 2, y 0 / y 2] d = 0 := by
  classical
  -- the ideal generated by the substituted equations, and a finite generating set
  obtain ⟨T, hT⟩ : (Ideal.span (sub3 '' F) : Ideal (Polynomial (R2 K))).FG :=
    IsNoetherian.noetherian _
  haveI : IsPrincipalIdealRing (Polynomial (L K)) := EuclideanDomain.to_principal_ideal_domain
  -- the extended ideal is principal
  obtain ⟨G, hG⟩ : ∃ G : Polynomial (L K),
      Ideal.map φL (Ideal.span (sub3 '' F)) = Ideal.span {G} :=
    ⟨_, (Submodule.IsPrincipal.span_singleton_generator _).symm⟩
  have hTdvd : ∀ t ∈ T, G ∣ φL t := by
    intro t ht
    have : φL t ∈ Ideal.map φL (Ideal.span (sub3 '' F)) :=
      Ideal.mem_map_of_mem _ (hT ▸ Ideal.subset_span ht)
    rw [hG] at this
    exact Ideal.mem_span_singleton.1 this
  -- a ring hom killing the generators kills the ideal
  have hIvanish : ∀ σ : Polynomial (R2 K) →+* K, (∀ t ∈ T, σ t = 0) →
      ∀ g ∈ Ideal.span (sub3 '' F), σ g = 0 := by
    intro σ hσ g hg
    have hle : Ideal.span (sub3 '' F) ≤ RingHom.ker σ := by
      rw [← hT, Ideal.span_le]
      intro t ht
      exact RingHom.mem_ker.2 (hσ t ht)
    exact RingHom.mem_ker.1 (hle hg)
  -- points of `V F ∩ U` kill the ideal
  have hspec : ∀ y ∈ V F, inU y → ∀ g ∈ Ideal.span (sub3 '' F),
      specialize (y 0 / y 2) (y 1 / y 2) (y 2) g = 0 := by
    intro y hy hU g hg
    have hz : y 2 ≠ 0 := hU.2.2
    have hsub : sub3 '' F ⊆ ↑(RingHom.ker (specialize (y 0 / y 2) (y 1 / y 2) (y 2))) := by
      rintro _ ⟨f, hf, rfl⟩
      rw [SetLike.mem_coe, RingHom.mem_ker, specialize_sub3, ← eq_scaled_of_ne_zero y hz]
      exact hy f hf
    exact RingHom.mem_ker.1 (Ideal.span_le.2 hsub hg)
  -- Case `G = 0`: every generator is zero, so `V F = 𝔸³`, contradicting an escaping point
  by_cases hG0 : G = 0
  · exfalso
    have hT0 : ∀ t ∈ T, t = 0 := by
      intro t ht
      have := hTdvd t ht
      rw [hG0, zero_dvd_iff] at this
      exact φL_injective (by rw [this, map_zero])
    obtain ⟨⟨u₀, v₀⟩, hE, -⟩ := exists_Eset_eval_ne_zero hfin (P := (1 : R2 K)) one_ne_zero
    have hmem : (![u₀ * 1, v₀ * 1, 1] : Fin 3 → K) ∈ V F := by
      intro f hf
      have h1 : sub3 f ∈ Ideal.span (sub3 '' F) := Ideal.subset_span ⟨f, hf, rfl⟩
      have h2 : specialize u₀ v₀ 1 (sub3 f) = 0 :=
        hIvanish _ (fun t ht => by rw [hT0 t ht, map_zero]) _ h1
      rwa [specialize_sub3] at h2
    exact not_reach_zero_of_Eset hE one_ne_zero (hnil _ hmem)
  -- clear the denominators of `G`
  obtain ⟨G₀, b, hb, hG₀⟩ := exists_clear G
  have hG₀0 : G₀ ≠ 0 := by
    intro h
    rw [h, map_zero] at hG₀
    exact mul_ne_zero (by rw [Ne, Polynomial.C_eq_zero]; exact algebraMap_ne_zero hb) hG0 hG₀.symm
  -- `C b * G₀` lies in the ideal, up to a further nonzero constant
  have hG₀mem : φL G₀ ∈ Ideal.map φL (Ideal.span (↑T : Set (Polynomial (R2 K)))) := by
    rw [hT, hG₀, hG]
    exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self G)
  obtain ⟨b', hb', g₀, hg₀mem, hg₀⟩ := exists_mem_span_of_mem_map T hG₀mem
  have hg₀eq : g₀ = Polynomial.C b' * G₀ := φL_injective (by rw [map_mul, φL_C, hg₀])
  -- strip the power of `z`: `G₀ = z^e * G₁` with `G₁(0) ≠ 0`
  obtain ⟨G₁, hG₁, hXG₁⟩ := Polynomial.exists_eq_pow_rootMultiplicity_mul_and_not_dvd G₀ hG₀0 0
  simp only [map_zero, sub_zero] at hG₁ hXG₁
  have hc₀ : G₁.coeff 0 ≠ 0 := fun h => hXG₁ (Polynomial.X_dvd_iff.2 h)
  have hG₁0 : G₁ ≠ 0 := fun h => hc₀ (by rw [h, Polynomial.coeff_zero])
  by_cases hdeg : G₁.natDegree = 0
  · -- `G₁ = C c₀`; then `C (b' c₀) * z^e ∈ I`, and `d := b' * c₀` works
    have hG₁C : G₁ = Polynomial.C (G₁.coeff 0) := Polynomial.eq_C_of_natDegree_eq_zero hdeg
    refine ⟨b' * G₁.coeff 0, mul_ne_zero hb' hc₀, ?_⟩
    intro y hy hU
    have hz : y 2 ≠ 0 := hU.2.2
    have h1 := hspec y hy hU g₀ (by rw [← hT]; exact hg₀mem)
    rw [hg₀eq, hG₁, hG₁C, map_mul, map_mul, specialize_C, specialize_C, map_pow,
      specialize_apply, Polynomial.map_X, Polynomial.eval_X] at h1
    rw [map_mul]
    rcases mul_eq_zero.1 h1 with h | h
    · rw [h, zero_mul]
    · rcases mul_eq_zero.1 h with h | h
      · exact absurd h (pow_ne_zero _ hz)
      · rw [h, mul_zero]
  · -- `G₁` has positive degree: produce an escaping point of `V F`, contradiction
    exfalso
    have hdeg' : 0 < G₁.natDegree := Nat.pos_of_ne_zero hdeg
    -- for each generator `t`: `C (bf t) * t = Hf t * G₁`
    have hTdvd₁ : ∀ t ∈ T, φL G₁ ∣ φL t := by
      intro t ht
      have h1 := hTdvd t ht
      have hu : IsUnit (Polynomial.C (algebraMap (R2 K) (L K) b)) := by
        rw [Polynomial.isUnit_C]; exact (algebraMap_ne_zero hb).isUnit
      have h2 : φL G₁ ∣ Polynomial.C (algebraMap (R2 K) (L K) b) * G := by
        rw [← hG₀, hG₁, map_mul]; exact dvd_mul_left _ _
      exact ((hu.dvd_mul_left).1 h2).trans h1
    choose! Hf bf hbf hrel using fun t (ht : t ∈ T) => exists_mul_eq_of_dvd (hTdvd₁ t ht)
    -- a point of `E` avoiding the leading coefficient, the constant term and all `bf t`
    have hP0 : G₁.leadingCoeff * G₁.coeff 0 * ∏ t ∈ T, bf t ≠ 0 :=
      mul_ne_zero (mul_ne_zero (Polynomial.leadingCoeff_ne_zero.2 hG₁0) hc₀)
        (Finset.prod_ne_zero_iff.2 (fun t ht => hbf t ht))
    obtain ⟨⟨u₀, v₀⟩, hE, hne⟩ := exists_Eset_eval_ne_zero hfin hP0
    simp only [map_mul, map_prod, ne_eq, mul_eq_zero, Finset.prod_eq_zero_iff, not_or,
      not_exists, not_and] at hne
    obtain ⟨⟨hlc, hc0⟩, hbt⟩ := hne
    -- the specialised `G₁` has a nonzero root `z₀`
    set g₁ : Polynomial K := Polynomial.map (MvPolynomial.eval ![v₀, u₀]) G₁ with hg₁
    have hg₁deg : g₁.natDegree = G₁.natDegree :=
      Polynomial.natDegree_map_of_leadingCoeff_ne_zero _ hlc
    have hg₁deg' : g₁.degree ≠ 0 := by
      have : 0 < g₁.natDegree := by rw [hg₁deg]; exact hdeg'
      exact (Polynomial.natDegree_pos_iff_degree_pos.1 this).ne'
    obtain ⟨z₀, hz₀⟩ := IsAlgClosed.exists_root g₁ hg₁deg'
    have hz₀0 : z₀ ≠ 0 := by
      rintro rfl
      apply hc0
      have := hz₀
      rw [Polynomial.IsRoot, ← Polynomial.coeff_zero_eq_eval_zero, hg₁, Polynomial.coeff_map] at this
      exact this
    -- the point `(u₀ z₀, v₀ z₀, z₀)` lies in `V F`
    have hkill : ∀ t ∈ T, specialize u₀ v₀ z₀ t = 0 := by
      intro t ht
      have h1 := congrArg (specialize u₀ v₀ z₀) (hrel t ht)
      rw [map_mul, map_mul, specialize_C] at h1
      have h2 : specialize u₀ v₀ z₀ G₁ = 0 := by
        rw [specialize_apply, ← hg₁]; exact hz₀
      rw [h2, mul_zero] at h1
      exact (mul_eq_zero.1 h1).resolve_left (hbt t ht)
    have hmem : (![u₀ * z₀, v₀ * z₀, z₀] : Fin 3 → K) ∈ V F := by
      intro f hf
      have h1 : sub3 f ∈ Ideal.span (sub3 '' F) := Ideal.subset_span ⟨f, hf, rfl⟩
      have h2 := hIvanish _ hkill _ h1
      rwa [specialize_sub3] at h2
    exact not_reach_zero_of_Eset hE hz₀0 (hnil _ hmem)

end ArithDyn.Nilpotence
