import ArithDyn.Derksen.RatFuncGalois

/-!
# The torus `𝔾_m^F` and the points `P^n` (paper §3)

Let `F` be a finite field with `q` elements and `K = F(t)`. The point `P^n ∈ K^F` of the torus
`𝔾_m^F` has coordinates `(t + a)^n` (`a ∈ F`, `n ∈ ℤ`). For `L = F(y_1, …, y_r)` and integer
weights `c : Fin r → ℤ` let `ν_a = ∏ᵢ (yᵢ + a)^{cᵢ} ∈ L`; the `F`-algebra map
`ν^# : F[T_a : a ∈ F] → L`, `T_a ↦ ν_a`, has kernel `I`, the ideal of the Zariski closure of the
image of `ν`.

* `aeval_Pn_eq_zero_of_mem_torusIdeal` (**forward direction**): if `n = ∑ᵢ cᵢ q^{kᵢ}` then every
  `f ∈ I` vanishes at `P^n`. The proof factors `ν^#` through the localization
  `S = F[y][(yᵢ + a)⁻¹]`, which maps injectively to `L` and maps to `K` by `yᵢ ↦ t^{q^{kᵢ}}`
  (this sends `yᵢ + a` to `(t + a)^{q^{kᵢ}}` by Frobenius, hence `ν_a ↦ (t + a)^n`).
* `isFundRec_aeval_Pn`: `n ↦ f(P^n)` is a fundamental bi-infinite recurrence over `K`.
* `isFundRec_zpow_sub`: `n ↦ ζ^n - ζ^m` is a fundamental bi-infinite recurrence.
-/

set_option autoImplicit false

namespace ArithDyn.Derksen

open Polynomial

variable {F : Type*} [Field F] [Fintype F]

/-- The point `P^n = ((t + a)^n)_{a ∈ F}` of the torus over `K = F(t)`. -/
noncomputable def Pn (n : ℤ) : F → RatFunc F :=
  fun a => (algebraMap (Polynomial F) (RatFunc F) (Polynomial.X + C a)) ^ n

/-- The function field `L = F(y_1, …, y_r)`. -/
abbrev Lfield (F : Type*) [Field F] (r : ℕ) := FractionRing (MvPolynomial (Fin r) F)

variable {r : ℕ} (c : Fin r → ℤ)

/-- `ν_a = ∏_i (y_i + a)^{c_i} ∈ L`. -/
noncomputable def νpt (a : F) : Lfield F r :=
  ∏ i, (algebraMap (MvPolynomial (Fin r) F) (Lfield F r) (MvPolynomial.X i + MvPolynomial.C a)) ^ c i

/-- `ν^# : F[T_a : a ∈ F] → L`, `T_a ↦ ν_a`. -/
noncomputable def νsharp : MvPolynomial F F →ₐ[F] Lfield F r := MvPolynomial.aeval (νpt c)

/-- The ideal `I = ker ν^#`. -/
noncomputable def torusIdeal : Ideal (MvPolynomial F F) := RingHom.ker (νsharp c).toRingHom

/-! ### Nonvanishing of the coordinates -/

section NonvanishingAux

omit [Fintype F]

/-- `y_i + a ≠ 0` in `F[y]`. -/
theorem mvX_add_C_ne_zero (i : Fin r) (a : F) :
    (MvPolynomial.X i + MvPolynomial.C a : MvPolynomial (Fin r) F) ≠ 0 := by
  intro h
  have h1 := congrArg (MvPolynomial.coeff (Finsupp.single i 1)) h
  rw [MvPolynomial.coeff_add, MvPolynomial.coeff_X, MvPolynomial.coeff_C,
    if_neg (fun h0 => Finsupp.single_ne_zero.2 one_ne_zero h0.symm), add_zero,
    MvPolynomial.coeff_zero] at h1
  exact one_ne_zero h1

theorem algebraMap_mvX_add_C_ne_zero (i : Fin r) (a : F) :
    algebraMap (MvPolynomial (Fin r) F) (Lfield F r) (MvPolynomial.X i + MvPolynomial.C a) ≠ 0 :=
  (map_ne_zero_iff _ (IsFractionRing.injective _ _)).2 (mvX_add_C_ne_zero i a)

theorem νpt_ne_zero (a : F) : νpt c a ≠ 0 := by
  unfold νpt
  rw [Finset.prod_ne_zero_iff]
  intro i _
  exact zpow_ne_zero _ (algebraMap_mvX_add_C_ne_zero i a)

/-- `t + a ≠ 0` in `F(t)`. -/
theorem algebraMap_X_add_C_ne_zero (a : F) :
    algebraMap (Polynomial F) (RatFunc F) (Polynomial.X + C a) ≠ 0 :=
  RatFunc.algebraMap_ne_zero (Polynomial.X_add_C_ne_zero a)

end NonvanishingAux

/-- Frobenius: `(X + a)^{q^k} = X^{q^k} + a` in `F[X]`, where `q = |F|`. -/
theorem X_add_C_pow_card_pow (a : F) (k : ℕ) :
    (Polynomial.X + C a : Polynomial F) ^ Fintype.card F ^ k =
      Polynomial.X ^ Fintype.card F ^ k + C a := by
  obtain ⟨p, hp, e, hpe, hcard⟩ := FiniteField.card' F
  haveI : Fact p.Prime := ⟨hpe⟩
  haveI : CharP F p := hp
  have hq : Fintype.card F ^ k = p ^ ((e : ℕ) * k) := by rw [hcard, pow_mul]
  rw [hq, add_pow_char_pow, ← Polynomial.C_pow, ← hq, FiniteField.pow_card_pow]

/-! ### Forward direction: `f ∈ I` vanishes at `P^n` for `n = ∑ᵢ cᵢ q^{kᵢ}` -/

section Forward

section LocalizationAux

omit [Fintype F]

variable (F r) in
/-- The multiplicative subset of `F[y]` generated by the `y_i + a`. -/
noncomputable def torusMonoid : Submonoid (MvPolynomial (Fin r) F) :=
  Submonoid.closure (Set.range fun x : Fin r × F => MvPolynomial.X x.1 + MvPolynomial.C x.2)

variable (F r) in
/-- The localization `S = F[y][(y_i + a)⁻¹ : i, a]`. -/
abbrev torusLoc := Localization (torusMonoid F r)

theorem mvX_add_C_mem_torusMonoid (i : Fin r) (a : F) :
    MvPolynomial.X i + MvPolynomial.C a ∈ torusMonoid F r :=
  Submonoid.subset_closure ⟨(i, a), rfl⟩

theorem torusMonoid_le_nonZeroDivisors :
    torusMonoid F r ≤ nonZeroDivisors (MvPolynomial (Fin r) F) := by
  refine Submonoid.closure_le.2 ?_
  rintro _ ⟨⟨i, a⟩, rfl⟩
  exact mem_nonZeroDivisors_of_ne_zero (mvX_add_C_ne_zero i a)

/-- A ring hom out of `F[y]` sending every `y_i + a` to a unit sends the whole multiplicative
set to units. -/
theorem isUnit_of_mem_torusMonoid {R : Type*} [CommRing R] (g : MvPolynomial (Fin r) F →+* R)
    (hg : ∀ (i : Fin r) (a : F), IsUnit (g (MvPolynomial.X i + MvPolynomial.C a)))
    (y : torusMonoid F r) : IsUnit (g y) := by
  obtain ⟨y, hy⟩ := y
  unfold torusMonoid at hy
  show IsUnit (g y)
  induction hy using Submonoid.closure_induction with
  | mem x hx =>
    obtain ⟨⟨i, a⟩, rfl⟩ := hx
    exact hg i a
  | one => simp
  | mul x y _ _ hx hy =>
    rw [map_mul]
    exact hx.mul hy

/-! #### The injection `ι' : S → L` -/

theorem isUnit_algebraMap_Lfield_of_mem (y : torusMonoid F r) :
    IsUnit (algebraMap (MvPolynomial (Fin r) F) (Lfield F r) y) :=
  isUnit_of_mem_torusMonoid _
    (fun i a => isUnit_iff_ne_zero.2 (algebraMap_mvX_add_C_ne_zero i a)) y

/-- `ι' : S → L`, the canonical map from the partial localization to the fraction field. -/
noncomputable def torusLocToL : torusLoc F r →+* Lfield F r :=
  IsLocalization.lift (M := torusMonoid F r) (S := torusLoc F r) isUnit_algebraMap_Lfield_of_mem

theorem torusLocToL_algebraMap (x : MvPolynomial (Fin r) F) :
    torusLocToL (algebraMap (MvPolynomial (Fin r) F) (torusLoc F r) x) =
      algebraMap (MvPolynomial (Fin r) F) (Lfield F r) x :=
  IsLocalization.lift_eq _ x

theorem torusLocToL_injective : Function.Injective (torusLocToL (F := F) (r := r)) := by
  unfold torusLocToL
  rw [IsLocalization.lift_injective_iff]
  intro x y
  rw [(IsLocalization.injective (torusLoc F r) torusMonoid_le_nonZeroDivisors).eq_iff,
    (IsFractionRing.injective (MvPolynomial (Fin r) F) (Lfield F r)).eq_iff]

/-! #### The units `y_i + a` of `S` and the points `w_a = ∏ᵢ (yᵢ + a)^{cᵢ} ∈ S` -/

theorem isUnit_algebraMap_mvX_add_C (i : Fin r) (a : F) :
    IsUnit (algebraMap (MvPolynomial (Fin r) F) (torusLoc F r)
      (MvPolynomial.X i + MvPolynomial.C a)) :=
  IsLocalization.map_units (torusLoc F r) (⟨_, mvX_add_C_mem_torusMonoid i a⟩ : torusMonoid F r)

/-- The unit `y_i + a` of `S`. -/
noncomputable def torusUnit (i : Fin r) (a : F) : (torusLoc F r)ˣ :=
  (isUnit_algebraMap_mvX_add_C i a).unit

theorem coe_torusUnit (i : Fin r) (a : F) :
    (torusUnit i a : torusLoc F r) =
      algebraMap (MvPolynomial (Fin r) F) (torusLoc F r) (MvPolynomial.X i + MvPolynomial.C a) :=
  IsUnit.unit_spec _

/-- `w_a = ∏ᵢ (yᵢ + a)^{cᵢ} ∈ S` (a product of integer powers of units). -/
noncomputable def wpt (a : F) : torusLoc F r :=
  ((∏ i, torusUnit i a ^ c i : (torusLoc F r)ˣ) : torusLoc F r)

/-- Any ring hom `φ : S → R'` into a field sends `w_a` to `∏ᵢ φ(yᵢ + a)^{cᵢ}`. -/
theorem map_wpt {R' : Type*} [Field R'] (φ : torusLoc F r →+* R') (a : F) :
    φ (wpt c a) = ∏ i, (φ (algebraMap (MvPolynomial (Fin r) F) (torusLoc F r)
      (MvPolynomial.X i + MvPolynomial.C a))) ^ c i := by
  have h : φ (wpt c a) =
      ((Units.map (φ : torusLoc F r →* R') (∏ i, torusUnit i a ^ c i) : R'ˣ) : R') := rfl
  rw [h, map_prod, Units.coe_prod]
  refine Finset.prod_congr rfl (fun i _ => ?_)
  rw [map_zpow, Units.val_zpow_eq_zpow_val]
  show (φ (torusUnit i a : torusLoc F r)) ^ c i = _
  rw [coe_torusUnit]

theorem torusLocToL_wpt (a : F) : torusLocToL (wpt c a) = νpt c a := by
  rw [map_wpt]
  unfold νpt
  refine Finset.prod_congr rfl (fun i _ => ?_)
  rw [torusLocToL_algebraMap]

end LocalizationAux

/-! #### The specialization `σ' : S → F(t)`, `y_i ↦ t^{q^{k_i}}` -/

/-- `σ : F[y] → F(t)`, `y_i ↦ t^{q^{k_i}}`. -/
noncomputable def σpoly (k : Fin r → ℕ) : MvPolynomial (Fin r) F →ₐ[F] RatFunc F :=
  MvPolynomial.aeval
    (fun i => algebraMap (Polynomial F) (RatFunc F) (Polynomial.X ^ Fintype.card F ^ k i))

/-- `σ(y_i + a) = t^{q^{k_i}} + a = (t + a)^{q^{k_i}}`. -/
theorem σpoly_X_add_C (k : Fin r → ℕ) (i : Fin r) (a : F) :
    σpoly k (MvPolynomial.X i + MvPolynomial.C a) =
      algebraMap (Polynomial F) (RatFunc F) (Polynomial.X + C a) ^ Fintype.card F ^ k i := by
  rw [← map_pow, X_add_C_pow_card_pow, map_add, map_add]
  simp only [σpoly, MvPolynomial.aeval_X, MvPolynomial.aeval_C]
  rw [RatFunc.algebraMap_eq_C, RatFunc.algebraMap_C]

theorem isUnit_σpoly_of_mem (k : Fin r → ℕ) (y : torusMonoid F r) :
    IsUnit ((σpoly (F := F) k).toRingHom y) :=
  isUnit_of_mem_torusMonoid _ (fun i a => by
    show IsUnit (σpoly k (MvPolynomial.X i + MvPolynomial.C a))
    rw [σpoly_X_add_C]
    exact isUnit_iff_ne_zero.2 (pow_ne_zero _ (algebraMap_X_add_C_ne_zero a))) y

/-- `σ' : S → F(t)`, the extension of `σ` to the localization. -/
noncomputable def σloc (k : Fin r → ℕ) : torusLoc F r →+* RatFunc F :=
  IsLocalization.lift (M := torusMonoid F r) (S := torusLoc F r) (isUnit_σpoly_of_mem k)

theorem σloc_algebraMap (k : Fin r → ℕ) (x : MvPolynomial (Fin r) F) :
    σloc k (algebraMap (MvPolynomial (Fin r) F) (torusLoc F r) x) = σpoly k x :=
  IsLocalization.lift_eq (isUnit_σpoly_of_mem k) x

/-- `∏ᵢ (x^{eᵢ})^{dᵢ} = x^{∑ᵢ dᵢ eᵢ}` for `x ≠ 0`. -/
theorem prod_pow_zpow_eq_zpow_sum {K : Type*} [Field K] {x : K} (hx : x ≠ 0) {ι : Type*}
    (s : Finset ι) (d : ι → ℤ) (e : ι → ℕ) :
    ∏ i ∈ s, (x ^ e i) ^ d i = x ^ (∑ i ∈ s, d i * (e i : ℤ)) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | insert a s ha ih =>
    rw [Finset.prod_insert ha, Finset.sum_insert ha, ih, zpow_add₀ hx, ← zpow_natCast x (e a),
      ← zpow_mul, mul_comm (e a : ℤ)]

/-- `σ'(w_a) = ∏ᵢ ((t + a)^{q^{kᵢ}})^{cᵢ} = (t + a)^n`, `n = ∑ᵢ cᵢ q^{kᵢ}`. -/
theorem σloc_wpt (k : Fin r → ℕ) (a : F) :
    σloc k (wpt c a) = Pn (∑ i, c i * (Fintype.card F : ℤ) ^ k i) a := by
  rw [map_wpt]
  simp only [σloc_algebraMap, σpoly_X_add_C]
  unfold Pn
  rw [prod_pow_zpow_eq_zpow_sum (algebraMap_X_add_C_ne_zero a)]
  simp only [Nat.cast_pow]

/-- **Forward direction.** For `n = ∑ᵢ cᵢ q^{kᵢ}` (`q = |F|`), every `f ∈ I` vanishes at `P^n`. -/
theorem aeval_Pn_eq_zero_of_mem_torusIdeal (k : Fin r → ℕ) {f : MvPolynomial F F}
    (hf : f ∈ torusIdeal c) :
    MvPolynomial.aeval (Pn (∑ i, c i * (Fintype.card F : ℤ) ^ k i)) f = 0 := by
  have h0 : νsharp c f = 0 := RingHom.mem_ker.1 hf
  -- `ν^#(f) = ι'(f(w))`
  have hL : torusLocToL (MvPolynomial.aeval (wpt c) f) = νsharp c f := by
    show torusLocToL (MvPolynomial.aeval (wpt c) f) = MvPolynomial.aeval (νpt c) f
    rw [MvPolynomial.aeval_def, MvPolynomial.aeval_def, MvPolynomial.eval₂_comp_left]
    congr 1
    · ext b
      rw [RingHom.comp_apply, IsScalarTower.algebraMap_apply F (MvPolynomial (Fin r) F)
        (torusLoc F r), torusLocToL_algebraMap,
        ← IsScalarTower.algebraMap_apply F (MvPolynomial (Fin r) F) (Lfield F r)]
    · funext a
      exact torusLocToL_wpt c a
  -- hence `f(w) = 0` in `S` by injectivity of `ι'`
  have hS : MvPolynomial.aeval (wpt c) f = 0 :=
    torusLocToL_injective (by rw [hL, h0, map_zero])
  -- and `σ'(f(w)) = f(P^n)`
  have hK : σloc k (MvPolynomial.aeval (wpt c) f) =
      MvPolynomial.aeval (Pn (∑ i, c i * (Fintype.card F : ℤ) ^ k i)) f := by
    rw [MvPolynomial.aeval_def, MvPolynomial.aeval_def, MvPolynomial.eval₂_comp_left]
    congr 1
    · ext b
      rw [RingHom.comp_apply, IsScalarTower.algebraMap_apply F (MvPolynomial (Fin r) F)
        (torusLoc F r), σloc_algebraMap, AlgHom.commutes]
    · funext a
      exact σloc_wpt c k a
  rw [← hK, hS, map_zero]

end Forward

/-! ### Recurrences -/

/-- Geometric sequences are fundamental recurrences (annihilator `X - b`). -/
theorem IsFundRec.geometric {K : Type*} [Field K] {b : K} (hb : b ≠ 0) :
    IsFundRec (fun n : ℤ => b ^ n) := by
  refine ⟨Polynomial.X - C b, Polynomial.monic_X_sub_C b, ?_, fun n => ?_⟩
  · rw [Polynomial.coeff_sub, Polynomial.coeff_X_zero, Polynomial.coeff_C_zero, zero_sub,
      neg_ne_zero]
    exact hb
  · rw [Polynomial.natDegree_X_sub_C, Finset.sum_range_succ, Finset.sum_range_succ,
      Finset.sum_range_zero]
    simp only [Polynomial.coeff_sub, Polynomial.coeff_X_zero, Polynomial.coeff_X_one,
      Polynomial.coeff_C_zero, Polynomial.coeff_C_ne_zero one_ne_zero, Nat.cast_zero,
      Nat.cast_one, add_zero, zpow_add_one₀ hb]
    ring

omit [Fintype F] in
/-- `n ↦ f(P^n)` is a fundamental recurrence over `F(t)`. -/
theorem isFundRec_aeval_Pn (f : MvPolynomial F F) :
    IsFundRec (fun n : ℤ => MvPolynomial.aeval (Pn n) f) := by
  induction f using MvPolynomial.induction_on with
  | C b =>
    simp only [MvPolynomial.aeval_C]
    exact IsFundRec.const _
  | add p q hp hq =>
    simp only [map_add]
    exact hp.add hq
  | mul_X p a hp =>
    simp only [map_mul, MvPolynomial.aeval_X]
    exact hp.mul (IsFundRec.geometric (algebraMap_X_add_C_ne_zero a))

/-- `n ↦ ζ^n - ζ^m` is a fundamental recurrence. -/
theorem isFundRec_zpow_sub {K : Type*} [Field K] {ζ : K} (hζ : ζ ≠ 0) (m : ℤ) :
    IsFundRec (fun n : ℤ => ζ ^ n - ζ ^ m) := by
  have := (IsFundRec.geometric hζ).add (IsFundRec.const (-ζ ^ m))
  simpa only [sub_eq_add_neg] using this

end ArithDyn.Derksen
